= Glossary

== Pairing

[IMPORTANT]
====
Before the two nodes are paired, we are unable to determine what node is the data source and what node is the destination.
To avoid confusion, we use *node A* and *node B* when referring to the two nodes.
====

Pair URI::
    The URI identifier that identifies *node A* in order to initialize the pairing process.

Node A::
    The node that wishes to include another node in it's federated network -- the node that initialized the pairing process.

Node B::
    The node that wishes to join the federated network.

NodeID A::
    Node ID of the federated node A.

NodeID B::
    Node ID of the federated node B.

Token A::
    The authentication token to access protected resources on node A.

Token B::
    The authentication token to access protected resources on node B.

== Data exchange

Origin node::
    The node that **shares the data** to the other node.
    If node A requests data from node B, node B is origin, as it contains the data.

Destination node::
    The node that **receives the data** from the origin node.
    If node A requests data from node B, node A is destination as it receives the data.

== Federated node

Node status::
    The current status of the federated node.
    Can be one of the following:

    * *Pending*: the node is prepared and is waiting for the pairing process.
    * *Pair requested*: the node is involved in the pairing process; either by initializing it, or by receiving a handshake request.
    * *paired*: the node pairing process is complete; either by confirming the handshake request or by receiving a handshake complete request.

Structure sync status::
    The current status of the structure sync.
    Can be one of the following:

    * *Syncing*: the node is currently syncing structures from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.

Data sync status::
    The current status of the data sync.
    Can be one of the following:

    * *Syncing*: the node is currently syncing data from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.
