= Glossary

== Pairing

[IMPORTANT]
====
Before the two nodes are paired, we are unable to determine what node is the data source and what node is the destination.
To avoid confusion, we use *node A* and *node B* when referring to the two nodes.
====

Pair URI::
    The URI identifier generated by *node A* that is used by *node B* to initialize the pairing process.

Node A::
    The node that created a *pair URI* to initialize the pairing process.

Node B::
    The node that uses the *pair URI* to initialize the pairing process.

NodeID A::
    The *federated node ID* that belongs to *node A*.

NodeID B::
    The *federated node ID* that belongs to *node B*.

Token A::
    The authentication token used by *node B* to access protected resources on *node A*.
    *Token A* is generated by *node A*.

Token B::
    The authentication token used by *node A* to access protected resources on *node B*.
    *Token B* is generated by *node B*.

== Data exchange

[NOTE]
====
A federated network is always *bidirectional* which makes the terms *origin node* and *destination node* relative based on the context.
====

Origin node::
    The *origin node* is the node that *provides the data*.
    If node A requests data from *node B*, node B *is origin*, as it provides the data.

Destination node::
    The *destination node* is the node that *is requesting data*.
    If *node A* requests data from node B, node A *is destination* as it requests the data.

== Federated node

Node status::
    Node status represents the current *status of the federated node*.
    The status can be one of the following:

    * *Pending*: the node is prepared and is waiting for the pairing process.
    * *Pair requested*: the node is involved in the pairing process; either by initializing it or by receiving a handshake request.
    * *paired*: the node pairing process is complete; either by confirming the handshake request or by receiving a complete handshake request.

Structure sync status::
    The current status of the structure sync.
    Can be one of the following:

    * *Syncing*: the node is currently syncing structures from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.

Data sync status::
    The current status of the data sync.
    Can be one of the following:

    * *Syncing*: the node is currently syncing data from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.
