include::../../variables.adoc[]

= {PRODUCT_NAME} Federation

.An abstract overview over the entire federation system.
[plantuml,federation-overview,svg,role=sequence]
----
@startuml
skinparam ParticipantPadding 50
participant "Node A\n(Origin Node)" as NodeA
participant "Node B\n(Destination Node)" as NodeB

== Node pairing ==
NodeA <-> NodeB: Pair nodes
note over NodeA, NodeB: The nodes exchange identity and authentication credentials via a node handshake
...
== Structure syncing ==
NodeA -> NodeA: Expose structures
note over NodeA
Origin node determines what structures
it wishes to expose to the destination node.
end note
NodeA -> NodeB: Structure sync

NodeB -> NodeB: Module mapping
note over NodeB
Destination node determines what origin fields
should map to what destination fields.
end note
...
== Data syncing ==
NodeA -> NodeB: Data sync

@enduml
----

Node pairing::
    <<node-pairing,Node pairing>> is the process of establishing a *federated network* between two nodes.
    Nodes in a federated network are able to *<<federation-security,securely>> exchange information*.
    Node pairing consists of two steps: <<pair-step1,node identification>> and <<pair-step2,node handshake>> that assure a secure exchange of authentication credentials.

Structure syncing::
    <<structure-syncing,Structure syncing>> is the process of determining the data structure the *origin node* is sharing with us, the *destination node*.
    The origin node has *full control* of what information it wishes to share with its destination nodes.
    The destination node has *full control* of *what information* we wish to collect and *how it should be stored*.
    This allows us to share information between systems that may have a completely different data model structure.

Data syncing::
    <<data-syncing,Data syncing>> is the process of fetching the shared data from the *origin node* and storing it on the *destination node*.
    The origin node provides data based on rules that specify *what structures* the destination node is allowed to access and the *<<federation-access-control,access control>> facility* that assures any sensitive information is excluded.
    The destination node stores the provided data based on its *field mapping rules*.

:leveloffset: +1

include::glossary.adoc[]

include::security.adoc[]

// include::logging.adoc[]

include::node_pair.adoc[]

include::structure_sync.adoc[]

include::data_sync.adoc[]

include::actionlog/index.adoc[]

include::api/index.adoc[]

include::store/index.adoc[]

:leveloffset: -1

