include::../../variables.adoc[]

[#rfc:federation:node-pair]
= Node pairing

Node pairing is the process of establishing a federated network between two {PRODUCT_NAME} nodes with the intent of secure data sharing.
The process consists of two steps:

Node identification::
    <<pair-step1>> exchanges necessary information about the two nodes so that they can establish a connection.

Node handshake::
    <<pair-step2>> exchanges authentication parameters that the federated nodes use to share protected resources.

.The diagram outlines the entire node pairing process; from node identification to node handshake.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

== Node identification ==
AdministratorA->NodeA: Register federated node B
AdministratorA->NodeA: Request node pairing URI
note right of AdministratorA
Administrator A sends the node pairing URI
to administrator B via a secure channel.
end note
AdministratorA-->AdministratorB: Send node pair URI
...
note left of AdministratorB
Administrator B registers node A
using the node pair URI.
end note
AdministratorB->NodeB: Register federated node A

== Node handshake ==
AdministratorB->NodeB: Initialize the handshake
note over NodeB #FFAAAA
Prepare the node's state for a
federated network.
end note

NodeB->NodeA: Request handshake
NodeA-->AdministratorA: Notify administrator A
note right of AdministratorA #ffffff
Administrator A should manually
approve the handshake.
end note
...
AdministratorA->NodeA: Approve handshake request
note over NodeA #FFAAAA
Prepare the node's state for a
federated network.
end note
NodeA->NodeB: Complete handshake
@enduml
----

[#pair-step1]
== Node identification

[IMPORTANT]
====
No authentication tokens are exchanged in during the identification step.
====

.The diagram outlines the node identification step of the node pairing process.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

AdministratorA->NodeA: Register federated node B
AdministratorA->NodeA: Request node pairing URI
note right of AdministratorA
Administrator A sends the node pairing URI
to administrator B via a secure channel.
end note
AdministratorA-->AdministratorB: Send node pair URI
...
note left of AdministratorB
Administrator B registers node A
using the node pair URI.
end note
AdministratorB->NodeB: Register federated node A
@enduml
----

[#pair-step1-1]
=== *Node A registers the federated node B*

*Node A* creates a new federated node that identifies *node B* by providing it's parameters to this <<node-create-params,API endpoint>>.
This creates a new *pending federation node* on node A.

[#pair-step1-2]
=== *Generate node pair URI*

See the <<node-create-uri,API reference>>.

*Node A* creates a *node pair URI* that is used by *node B* to identify *node A*.
The generated pair URI is sent to the *node B administrator* via some secure channel.
The node pair URI is defined as:

[source,bash]
----
corteza+federation://$NODE_ID:$PAIRING_TOKEN@$HOST_A/$API_FEDERATION_PATH?$QS_METADATA

# NODE_ID <1>
# PAIRING_TOKEN <2>
# HOST_A <3>
# API_FEDERATION_PATH <4>
# QS_METADATA <5>
----
<1> The nodeID A that was generated in <<pair-step1-1,step 1>>.
<2> An OTT token that is generated in this step.
<3> Node A's host address.
<4> Node A's path to the federation API endpoint.
<5> Metadata provided as a query string.

[IMPORTANT]
====
The OTT token generated in this step is used for initial authentication before the two nodes exchange their authentication tokens.
====

[#pair-step1-3]
=== *Node B registers federated node A*

*Node B* creates a new federated node that identifies *node A*.
The node is created from the *node pair URI* that was generated by *node A* and provided to *node B* via some secure channel (<<node-create-uri,API endpoint>>).

[#pair-step2]
== Node handshake

.The diagram outlines the node handshake step of the node pairing process.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

AdministratorB->NodeB: Initialize the handshake
note over NodeB #FFAAAA
Prepare the node's state for a
federated network.
end note

NodeB->NodeA: Request handshake
NodeA-->AdministratorA: Notify administrator A
note right of AdministratorA #ffffff
Administrator A should manually
approve the handshake.
end note
...
AdministratorA->NodeA: Approve handshake request
note over NodeA #FFAAAA
Prepare the node's state for a
federated network.
end note
NodeA->NodeB: Complete handshake
@enduml
----

[#pair-step2-1]
=== *Node B initializes pairing with node A*

See the <<node-pair-handshake-init,API reference>>.

*Node B administrator* initializes the node pairing process.
*Node B* configures its state to allow a federated network with *node A*.
In this step, we:

* Create a *system user* that serves requests performed by *node A*.
* Create an authentication token (*token B*) that is used by *node A* when accessing protected resources.

[#pair-step2-2]
=== *Node B sends a pair request to node A*

[IMPORTANT]
====
Since the nodes haven't yet exchanged their authentication tokens, the pairing request is performed outside of the standard authentication facility.

The OTT token created in the <<pair-step1-2,node identification step>> is used for authentication.
====

*Node B* sends a pairing request to *node A* (see the <<node-pair-handshake-request,API endpoint>>).
The request provides the parameters that we generate in <<pair-step2-1,the previous step>>.

[#pair-step2-3]
=== *Node A confirms the pair request*

See the <<node-pair-handshake-confirm,API reference>>.

*Node A administrator* manually confirms the pairing request that was sent by *node B*.
*Node A* configures its state to allow a federated network with *node B*.
In this step, we:

* Create a *system user* that serves requests performed by *node B*.
* Create an authentication token (*token A*) that is used by *node B* when accessing protected resources.

[#pair-step2-4]
=== *Node A completes the pair process*

See the <<node-pair-handshake-complete,API reference>>.

*Node A* completes the pairing process by sending it's authentication parameters created in <<pair-step2-3,the previous step>> to *node B*.
Node B updates its federated node and completes the pairing process.

[NOTE]
====
This request already uses *token B* to authenticate the request.
====
